application:
  env: dev
  host: 0.0.0.0
  port: 8080

mysqldb:
  ip: 123.207.71.88
  port: 3306
  username: root
  password:
  database: cst_ucenter

mongodb:
  ip: 192.168.2.240
  port: 11708
  username:
  password:
  options:
  database: cst_ucenter
